In [1]:
import numpy


  # Dictionary

In [2]:
d={'key1':10,'key2':'20'}

In [3]:
d

{'key1': '10', 'key2': '20'}

In [4]:
d['key1']

'10'

In [5]:
if(1<2):
    print('milee')

milee


In [7]:
if True:
    print('true')

true


In [10]:
def tim(var):
    return var*2

In [13]:
out=tim(5)

In [14]:
out

10

# Tuple Unpacking


In [19]:
x=[(1,2),(3,4)]
for item in x:
    print item
    
    

(1, 2)
(3, 4)


In [20]:
for a,b in x:
    print a
    print b

1
2
3
4


# Numpy Arrays

In [24]:
import numpy as np

In [22]:
my_list=[1,2,3]

In [23]:
my_list

[1, 2, 3]

In [25]:
arr=np.array(my_list)

In [26]:
arr

array([1, 2, 3])

In [27]:
my_math=[[1,2,3],[4,5,6],[6,7,8]]

In [28]:
np.array(my_math)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [30]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [31]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [32]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [33]:
np.ones((0))

array([], dtype=float64)

In [34]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [35]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [36]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [37]:
np.random.rand(5)

array([ 0.87712492,  0.93787113,  0.86824395,  0.59484649,  0.81087323])

In [38]:
np.random.rand(5,5)

array([[ 0.27834835,  0.97105985,  0.95346817,  0.70476363,  0.51414024],
       [ 0.83324435,  0.03431516,  0.864631  ,  0.46843114,  0.04284214],
       [ 0.67893747,  0.82411778,  0.97291333,  0.25017391,  0.95031093],
       [ 0.05016235,  0.04154848,  0.18131405,  0.37597624,  0.27212766],
       [ 0.90616309,  0.34433161,  0.05721941,  0.14106062,  0.02948883]])

In [39]:
np.random.randn(2)

array([ 0.49421998, -0.39341958])

In [40]:
np.random.randn(4,4)

array([[-0.49034001,  0.73373878, -0.7686815 ,  1.85592263],
       [-1.27835216, -0.32363439,  2.0883997 , -0.0536099 ],
       [-1.40474313, -0.983766  , -1.80278148,  1.08087752],
       [-0.56268005,  0.11255287, -0.16963798,  0.39627609]])

In [42]:
np.random.randint(1,100,10)

array([74, 15, 50, 18, 92, 68, 90, 60,  9, 47])

In [43]:
arr=np.arange(25)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
ranarr=np.random.randint(0,50,10)

In [46]:
ranarr

array([20,  6, 34, 19, 18, 11, 32, 38, 44, 26])

In [47]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
ranarr

array([20,  6, 34, 19, 18, 11, 32, 38, 44, 26])

In [50]:
ranarr.max()

44

In [51]:
ranarr.min()

6

In [52]:
ranarr

array([20,  6, 34, 19, 18, 11, 32, 38, 44, 26])

In [53]:
ranarr.argmax()

8

In [54]:
ranarr.argmin()

1

In [55]:
arr.shape

(25,)

In [56]:
arr=arr.reshape(5,5)

In [57]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arr.shape

(5, 5)

In [59]:
arr.dtype

dtype('int64')

In [61]:
from numpy.random import randint

In [62]:
randint(2,10)

5

In [63]:
import numpy as np

In [66]:
arr=np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [69]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [70]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [71]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [72]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr[1,2]

6

In [78]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])

# Conditional Selection

In [79]:
arr=np.arange(1,11)

In [80]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
bool_arr=arr > 5

In [84]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [85]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])